import type {
  BankAccount,
  Wallet,
  CreditCard,
  AccountTransfer,
  AccountActivity,
} from "./types"

function generateHistory(base: number, points = 7): { date: string; balance: number }[] {
  const history: { date: string; balance: number }[] = []
  let current = base
  const today = new Date()
  for (let i = points - 1; i >= 0; i--) {
    const d = new Date(today)
    d.setDate(d.getDate() - i * 7)
    const change = (Math.random() - 0.45) * 15000
    current += change
    history.push({
      date: d.toISOString().split("T")[0],
      balance: Math.round(current),
    })
  }
  return history
}

export const demoBankAccounts: BankAccount[] = [
  {
    id: "ba-1",
    bankName: "HDFC Bank",
    accountType: "Savings",
    accountNumber: "50100234567890",
    balance: 284750,
    currency: "INR",
    status: "active",
    lastUpdated: "2025-01-15T10:30:00Z",
    notes: "Primary salary account. Auto-sweep enabled.",
    history: generateHistory(270000),
  },
  {
    id: "ba-2",
    bankName: "State Bank of India",
    accountType: "Savings",
    accountNumber: "123456789012",
    balance: 94500,
    currency: "INR",
    status: "active",
    lastUpdated: "2025-01-14T16:45:00Z",
    notes: "Family expenses account.",
    history: generateHistory(88000),
  },
  {
    id: "ba-3",
    bankName: "ICICI Bank",
    accountType: "Current",
    accountNumber: "001234567890",
    balance: 425000,
    currency: "INR",
    status: "active",
    lastUpdated: "2025-01-15T09:00:00Z",
    notes: "Business current account.",
    history: generateHistory(400000),
  },
  {
    id: "ba-4",
    bankName: "Axis Bank",
    accountType: "Fixed Deposit",
    accountNumber: "912345678901",
    balance: 500000,
    currency: "INR",
    status: "active",
    lastUpdated: "2025-01-10T08:00:00Z",
    notes: "6-month FD maturing in March 2025.",
    history: generateHistory(500000, 4),
  },
  {
    id: "ba-5",
    bankName: "Kotak Mahindra",
    accountType: "Savings",
    accountNumber: "8123456789",
    balance: 3200,
    currency: "INR",
    status: "active",
    lastUpdated: "2025-01-13T11:20:00Z",
    notes: "Emergency buffer — low balance alert!",
    history: generateHistory(12000),
  },
  {
    id: "ba-6",
    bankName: "Punjab National Bank",
    accountType: "Savings",
    accountNumber: "612345678901",
    balance: 15000,
    currency: "INR",
    status: "inactive",
    lastUpdated: "2024-11-20T14:00:00Z",
    notes: "Dormant account. Plan to close.",
    history: generateHistory(15000, 3),
  },
]

export const demoWallets: Wallet[] = [
  {
    id: "w-1",
    name: "Cash in Hand",
    type: "cash",
    balance: 4500,
    currency: "INR",
    lastUpdated: "2025-01-15T08:00:00Z",
    notes: "Home cash reserve",
  },
  {
    id: "w-2",
    name: "Paytm Wallet",
    type: "digital",
    balance: 2850,
    currency: "INR",
    lastUpdated: "2025-01-14T19:30:00Z",
  },
  {
    id: "w-3",
    name: "PhonePe",
    type: "digital",
    balance: 12000,
    currency: "INR",
    lastUpdated: "2025-01-15T07:45:00Z",
  },
  {
    id: "w-4",
    name: "Google Pay",
    type: "digital",
    balance: 6750,
    currency: "INR",
    lastUpdated: "2025-01-13T21:00:00Z",
  },
  {
    id: "w-5",
    name: "Amazon Gift Card",
    type: "gift_card",
    balance: 2000,
    currency: "INR",
    lastUpdated: "2025-01-10T12:00:00Z",
    notes: "Expires Dec 2025",
  },
]

export const demoCreditCards: CreditCard[] = [
  {
    id: "cc-1",
    cardName: "ICICI Platinum",
    bankName: "ICICI Bank",
    cardNumberLast4: "4521",
    limit: 200000,
    used: 85000,
    currency: "INR",
    dueDate: "2025-01-25",
    minimumDue: 4250,
    lastPaymentDate: "2024-12-25",
    lastPaymentAmount: 60000,
    status: "active",
  },
  {
    id: "cc-2",
    cardName: "HDFC Millennia",
    bankName: "HDFC Bank",
    cardNumberLast4: "8812",
    limit: 150000,
    used: 120000,
    currency: "INR",
    dueDate: "2025-01-28",
    minimumDue: 6000,
    lastPaymentDate: "2024-12-28",
    lastPaymentAmount: 45000,
    status: "active",
  },
  {
    id: "cc-3",
    cardName: "SBI SimplySAVE",
    bankName: "SBI",
    cardNumberLast4: "3390",
    limit: 100000,
    used: 22000,
    currency: "INR",
    dueDate: "2025-02-05",
    minimumDue: 1100,
    lastPaymentDate: "2025-01-05",
    lastPaymentAmount: 25000,
    status: "active",
  },
  {
    id: "cc-4",
    cardName: "Axis Magnus",
    bankName: "Axis Bank",
    cardNumberLast4: "7743",
    limit: 500000,
    used: 45000,
    currency: "INR",
    dueDate: "2025-02-10",
    minimumDue: 2250,
    lastPaymentDate: "2025-01-10",
    lastPaymentAmount: 30000,
    status: "active",
  },
]

export const demoTransfers: AccountTransfer[] = [
  {
    id: "tr-1",
    fromAccountId: "ba-1",
    fromAccountName: "HDFC Bank",
    fromAccountType: "bank",
    toAccountId: "ba-2",
    toAccountName: "SBI",
    toAccountType: "bank",
    amount: 25000,
    currency: "INR",
    date: "2025-01-12",
    notes: "Monthly family support",
    fee: 0,
    status: "completed",
  },
  {
    id: "tr-2",
    fromAccountId: "ba-1",
    fromAccountName: "HDFC Bank",
    fromAccountType: "bank",
    toAccountId: "w-3",
    toAccountName: "PhonePe",
    toAccountType: "wallet",
    amount: 5000,
    currency: "INR",
    date: "2025-01-14",
    notes: "UPI load",
    fee: 0,
    status: "completed",
  },
  {
    id: "tr-3",
    fromAccountId: "w-2",
    fromAccountName: "Paytm Wallet",
    fromAccountType: "wallet",
    toAccountId: "ba-3",
    toAccountName: "ICICI Bank",
    toAccountType: "bank",
    amount: 2000,
    currency: "INR",
    date: "2025-01-10",
    notes: "Refund transfer",
    fee: 15,
    status: "completed",
  },
  {
    id: "tr-4",
    fromAccountId: "ba-3",
    fromAccountName: "ICICI Bank",
    fromAccountType: "bank",
    toAccountId: "ba-1",
    toAccountName: "HDFC Bank",
    toAccountType: "bank",
    amount: 75000,
    currency: "INR",
    date: "2025-01-08",
    notes: "Business revenue sweep",
    fee: 0,
    status: "completed",
  },
  {
    id: "tr-5",
    fromAccountId: "ba-2",
    fromAccountName: "SBI",
    fromAccountType: "bank",
    toAccountId: "w-1",
    toAccountName: "Cash in Hand",
    toAccountType: "wallet",
    amount: 3000,
    currency: "INR",
    date: "2025-01-05",
    notes: "ATM withdrawal",
    fee: 0,
    status: "completed",
  },
]

export const demoActivities: AccountActivity[] = [
  {
    id: "act-1",
    date: "2025-01-15",
    description: "Salary Credit - Employer",
    amount: 125000,
    type: "credit",
    category: "Income",
  },
  {
    id: "act-2",
    date: "2025-01-14",
    description: "Amazon.in Purchase",
    amount: 3499,
    type: "debit",
    category: "Shopping",
  },
  {
    id: "act-3",
    date: "2025-01-14",
    description: "Swiggy Order",
    amount: 680,
    type: "debit",
    category: "Food",
  },
  {
    id: "act-4",
    date: "2025-01-13",
    description: "Uber Ride",
    amount: 245,
    type: "debit",
    category: "Transport",
  },
  {
    id: "act-5",
    date: "2025-01-13",
    description: "Interest Credit",
    amount: 1240,
    type: "credit",
    category: "Interest",
  },
  {
    id: "act-6",
    date: "2025-01-12",
    description: "Rent Payment",
    amount: 22000,
    type: "debit",
    category: "Housing",
  },
  {
    id: "act-7",
    date: "2025-01-11",
    description: "Mutual Fund SIP",
    amount: 10000,
    type: "debit",
    category: "Investment",
  },
]

