export { default as Header } from "./Header"
export { default as Summary } from "./Summary"
export { default as GoalsList } from "./GoalsList"
export { default as DetailsDrawer } from "./DetailsDrawer"
export { default as AddModal } from "./AddModal"
export type { SavingsGoal, SavingsSummaryData, Contribution } from "./demo-data"
export { demoSavingsSummary, demoSavingsGoals, accountOptions } from "./demo-data"
